version: "3.7"


services:
  redis:
    restart: always
    image: redis:5.0
    volumes:
      - redis:/data
    env_file:
      - .env
    ports:
      - "6379:6379"
    # command: ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASS\""]

volumes:
  redis:
